[package]
name = "kas-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
kas = { version = "0.17.0", default-features = false, features = ["soft"] }
kas-widgets = "0.17.1"
rquickjs = { version = "0.14.0", features = ["loader"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
winit = "=0.31.0-beta.2"

[build-dependencies]
